---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'docker.io/ashish1981/ansible-runner:latest'
dependencies:
  galaxy: _build/requirements.yml
  system: _build/bindep.txt
  python: _build/requirements.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=docker.io/ashish1981/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000
    - RUN git lfs install
